### ISSUE TITLE
There are no links 

### ISSUE THREAD

**Issue by aakarshan-raj** [pegvin/6502#1]
No links that were on original website.

**Comment by pegvin** [comment]
ah hey, i'm aware of that if you can raise a pr, it'll take me some time since i have some other things to handle too.

**Comment by pegvin** [comment]
Hi @aakarshan-raj, i worked on the 6502 clone webpage and today i completed the whole cloning process, which you can access at https://pegvin.github.io/6502/.

also the content of this repositories are moved into a new repository mentioned in readme.
